version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    volumes:
      - ./flask:/usr/src/app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi app.ini'
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY: $SESSION_SECRET_KEY
    expose:
      - 8080
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: localhost
    restart: always
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask

volumes:
  postgres_data: